/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bycorp.clientesgestion;

import com.bycorp.dao.ClientesDAO;
import com.bycorp.models.Cliente;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author HP
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        scrolClientes = new javax.swing.JScrollPane();
        listClientes = new javax.swing.JList<>();
        nom = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        ape = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        ema = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Gestor de Clientes");
        panel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 575, 32));

        listClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listClientesMouseClicked(evt);
            }
        });
        scrolClientes.setViewportView(listClientes);

        panel.add(scrolClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 80, 222, 330));

        nom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nom.setText("Nombre: ");
        panel.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));
        panel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 80, 235, -1));

        ape.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ape.setText("Apellido: ");
        panel.add(ape, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        panel.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 235, -1));

        ema.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ema.setText("Email: ");
        panel.add(ema, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 40, 20));
        panel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 235, -1));
        panel.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 235, -1));

        tel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tel.setText("Telefono:");
        panel.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 20));

        eliminar.setText("Eliminar");
        eliminar.setEnabled(false);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        panel.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 80, 30));

        guardar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        panel.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listClientesMouseClicked
        if (!listClientes.isSelectionEmpty()) {
            eliminar.setEnabled(true);
        }
    }//GEN-LAST:event_listClientesMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Cliente c = new Cliente();
        
        if (!listClientes.isSelectionEmpty()) {
            c =(Cliente) (Object) listClientes.getModel().getElementAt(listClientes.getSelectedIndex());
            ClientesDAO dao = new ClientesDAO();
            dao.eliminarCliente(c.getId());
            actualizarLista();
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        if (validarCampos()) {
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String email = txtEmail.getText();
            String telefono = txtTelefono.getText();
            Cliente cliente = new Cliente(nombre, apellido, email, telefono);

            ClientesDAO c = new ClientesDAO();
            c.insertarCliente(cliente);

            actualizarLista();
            limpiarCajasDeTexto();
        }
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ape;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel ema;
    private javax.swing.JButton guardar;
    private javax.swing.JList<String> listClientes;
    private javax.swing.JLabel nom;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrolClientes;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void actualizarLista() {
        ClientesDAO dao = new ClientesDAO();
        List<Cliente> lista = dao.listarClientes();
        DefaultListModel datos = new DefaultListModel();
        
        for (int i = 0; i < lista.size(); i++) {
            datos.addElement(lista.get(i));
        }
        listClientes.setModel(datos);
    }

    private void limpiarCajasDeTexto() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtEmail.setText("");
        txtTelefono.setText("");
    }

    private boolean validarCampos() {
        if (txtNombre.getText().trim().equals("") || txtApellido.getText().trim().equals("") || txtEmail.getText().trim().equals("") || txtTelefono.getText().trim().equals("")) {
            JOptionPane.showInternalMessageDialog(null, "Revise los campos vacios", "Error en los campos", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }
}
